Alghoritm: LapSVM
Dataset: imdb
X_labeled shape: (30, 1000), X_unlabeled shape: (70, 1000)
y_labeled shape: (30,)
Training model
X_train shape: (30, 1000), X_unlabeled shape: (70, 1000)
y_train shape: (30,)

float() argument must be a string or a number, not 'csr_matrix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/main.py", line 101, in <module>
    train_model(model_name, model_function, dataset_name, preprocess_function, labeled_size, models_hyperparameters, results)
  File "scripts/main.py", line 33, in train_model
    results[model_name][dataset_name] = train_and_evaluate(dataset_name, model, X_labeled, y_labeled, X_unlabeled, X_test, y_test)
  File "C:\Users\kaami\Desktop\BSc_Thesis\scripts\model_training.py", line 24, in train_and_evaluate
    model.fit(X=X_train, y=y_train, unlabeled_X=X_unlabeled)
  File "C:\Users\kaami\AppData\Local\Programs\Python\Python37\lib\site-packages\LAMDA_SSL\Algorithm\Classification\LapSVM.py", line 81, in fit
    W = self.distance_function(self.X, self.X)
  File "C:\Users\kaami\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\metrics\pairwise.py", line 1166, in rbf_kernel
    X, Y = check_pairwise_arrays(X, Y)
  File "C:\Users\kaami\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\metrics\pairwise.py", line 153, in check_pairwise_arrays
    estimator=estimator,
  File "C:\Users\kaami\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\validation.py", line 738, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
ValueError: setting an array element with a sequence.